### PR TITLE
Fix ssl add config flow

### PR DESCRIPTION
**Pull request by devPeete**
## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New integration (thank you!)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Deprecation (breaking change to happen in the future)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast homeassistant tests`)
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

If the code communicates with devices, web services, or third-party tools:

- [ ] The [manifest file][manifest-docs] has all fields filled out correctly.  
      Updated and included derived files by running: `python3 -m script.hassfest`.
- [x] New or updated dependencies have been added to `requirements_all.txt`.  
      Updated by running `python3 -m script.gen_requirements_all`.
- [ ] For the updated dependencies - a link to the changelog, or at minimum a diff between library versions is added to the PR description.
- [x] Untested files have been added to `.coveragerc`.

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/core/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+-label%3Awaiting-for-upstream+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[manifest-docs]: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html
[quality-scale]: https://developers.home-assistant.io/docs/en/next/integration_quality_scale_index.html
[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by devPeete** [comment]
Basically, mine can be imported but the requests library from the nextcloud_monitor pypi package is blocking the function. If I use the NextcloudMonitorCustom class everything is working fine for me. Would appreciate a proper work around for thhat. Do you have any idea? I am not really familiar with asyncio.

Besides this, I did not do any of the CI/CD tests so far

**Comment by devPeete** [comment]
Okay, nvm. I added the async calls and from my side it should work. I have not tested self signed certificates yet, maybe I'll get this done by tomorrow. 
Basically the integration should work. Please have a review from your side and let me know your thoughts.

I would like to add the current stable version published from nextcloud as another sensor. I have not investigated in this.
Could you prepare the tests for this?

**Comment by devPeete** [comment]
Except testing the config flow, the developer checklist is completed, code is working locally.

**Comment by Hadatko** [comment]
@devPeete Thank you very much. But because you were on newer commit than me i got many files in PR which shouldn't be there so  i did rebase. Now we have merge conflicts.

**Comment by devPeete** [comment]
> @devPeete Thank you very much. But because you were on newer commit than me i got many files in PR which shouldn't be there so i did rebase. Now we have merge conflicts.

Yes, merge conflicts are ok. I would propose to take the integration folder from me and adopt the tests you've written. I am already using my files as custom integration and for me it works.

**Comment by Hadatko** [comment]
@devPeete In that case i think we are doing merge wrong way :D I should merge just tests into your repository

**Comment by devPeete** [comment]
> @devPeete In that case i think we are doing merge wrong way :D I should merge just tests into your repository

Would be ok for me aswell, we only need to post a new PR on homeassistant then.

**Comment by Hadatko** [comment]
I fixed merge conflict and took all your changes.

**Comment by devPeete** [comment]
Okay, will you adopt the test for the config_flow?

**Comment by Hadatko** [comment]
I will have time next week. Not earlier unfortunatelly.

**Comment by devPeete** [comment]
> I will have time next week. Not earlier unfortunatelly.

Okay, I will check if I have time tomorrow. Otherwise it will be next week for me aswell.
Can you tell me how I can execute the tests locally?

**Pull request merged**
